site_user_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: SiteUserBundle:Default:index }

fos_user_security_login:
    pattern:  /login.html
    defaults: { _controller: FOSUserBundle:Security:login }
    options:
        expose: true

fos_user_registration_register:
    pattern:  /register.html
    defaults: { _controller: FOSUserBundle:Registration:register }
    options:
        expose: true

fos_user_security_check:
    pattern:  /login_check
    defaults: { _controller: FOSUserBundle:Security:check }
    methods:  [POST]
    options:
        expose: true

user_unique_check:
    pattern:  /user_unique_check
    defaults: { _controller: SiteUserBundle:Registration:checkunique }
    options:
        expose: true

fos_user_registration_check_email:
    path:     /check-email
    defaults: { _controller: FOSUserBundle:Registration:checkEmail }
    methods:  [GET,POST]

fos_user_registration_confirm:
    path:     /confirm/{token}
    defaults: { _controller: FOSUserBundle:Registration:confirm }
    methods:  [GET]

fos_user_registration_confirmed:
    path:     /confirmed
    defaults: { _controller: FOSUserBundle:Registration:confirmed }